services:
  app:
    container_name: node-app
    build: 
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - VITE_NODE_ENV=development
      - TS_NODE_BASEURL=./dist
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${DB_PORT}:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
